version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_pass
    ports: ["5432:5432"]
    volumes: ["db_data:/var/lib/postgresql/data"]

  web:
    build: .
    environment:
      DJANGO_SECRET_KEY: devsecret
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "*"
      POSTGRES_DB: library_db
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_pass
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      SIMPLEJWT_ACCESS_LIFETIME_MIN: "320"
      SIMPLEJWT_REFRESH_LIFETIME_DAYS: "30"
    depends_on: [db]
    ports: ["8000:8000"]
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py createsuperuser --noinput || true &&
      python manage.py runserver 0.0.0.0:8000
      "
volumes:
  db_data:
